spring:
  config:
    activate:
      on-profile: mongodb

  data:
    mongodb:
      host: localhost
      port: 27017
      database: identity_service

    redis:
      host: localhost
      port: 6379
    elasticsearch:
      uris: http://localhost:9200

  cache:
    type: redis

autoconfigure:
  exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

server:
  port: 8080
  servlet:
    context-path: /identity
